- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: 8e0d7bab601ce6a8775ea98082938e60fc80eb7f
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: local
  hooks:
    - id: clang-format
      name: clang-format
      description: Format files with ClangFormat.
      entry: clang-format
      language: system
      files: \.(c|cc|cxx|cpp|h|hpp|hxx|java|js|m|proto)$
      args: ['-fallback-style=Google', '-i']
