- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: 8e0d7bab601ce6a8775ea98082938e60fc80eb7f
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: local
  hooks:
    - id: clang-format
      name: clang-format
      entry: clang-format -i
      language: system
      files: \.(h|hpp|cc|c|cpp)
