language: cpp
sudo: required
dist: trusty

os:
    - linux
    - osx
    
addons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
      - clang-format-3.8
      - build-essential
      - automake
      - libtool
      - ccache

script:
    - make scanner
    - make parser

notifications:
  email:
    on_success: change
    on_failure: always
