----------------------------------------
Table: Types
Name: int
----------------------------------------
Scope: 0
Type: int
Dimension: -
Parameters: -
Parameter types: -
Parameter dimensions: -
Return type: -

----------------------------------------
Table: Functions
Name: printi
----------------------------------------
Scope: 0
Type: -
Dimension: -
Parameters: [i]
Parameter types: [int]
Parameter dimensions: [0]
Return type: -

----------------------------------------
Table: Types
Name: float
----------------------------------------
Scope: 0
Type: float
Dimension: -
Parameters: -
Parameter types: -
Parameter dimensions: -
Return type: -

----------------------------------------
Table: Functions
Name: not
----------------------------------------
Scope: 0
Type: -
Dimension: -
Parameters: [i]
Parameter types: [int]
Parameter dimensions: [0]
Return type: int

----------------------------------------
Table: Functions
Name: flush
----------------------------------------
Scope: 0
Type: -
Dimension: -
Parameters: -
Parameter types: -
Parameter dimensions: -
Return type: -

----------------------------------------
Table: Functions
Name: exit
----------------------------------------
Scope: 0
Type: -
Dimension: -
Parameters: [i]
Parameter types: [int]
Parameter dimensions: [0]
Return type: -

----------------------------------------
Table: Temporaries
Name: $t0
----------------------------------------
Scope: 0
Type: int
Dimension: -
Parameters: -
Parameter types: -
Parameter dimensions: -
Return type: -

----------------------------------------
Table: Variables
Name: b
----------------------------------------
Scope: 0
Type: int
Dimension: -
Parameters: -
Parameter types: -
Parameter dimensions: -
Return type: -

----------------------------------------
Table: Constants
Name: 0
----------------------------------------
Scope: 0
Type: int
Dimension: -
Parameters: -
Parameter types: -
Parameter dimensions: -
Return type: -

----------------------------------------
Table: Variables
Name: a
----------------------------------------
Scope: 0
Type: int
Dimension: -
Parameters: -
Parameter types: -
Parameter dimensions: -
Return type: -

----------------------------------------
Table: Temporaries
Name: $t1
----------------------------------------
Scope: 0
Type: int
Dimension: -
Parameters: -
Parameter types: -
Parameter dimensions: -
Return type: -

----------------------------------------
Table: Constants
Name: 2
----------------------------------------
Scope: 0
Type: int
Dimension: -
Parameters: -
Parameter types: -
Parameter dimensions: -
Return type: -

