----------------------------------------
Table: Types
Name: int
----------------------------------------
Scope: 0
Type: int
Dimension: -
Parameters: -
Parameter types: -
Parameter dimensions: -
Return type: -

----------------------------------------
Table: Functions
Name: printi
----------------------------------------
Scope: 0
Type: -
Dimension: -
Parameters: [i]
Parameter types: [int]
Parameter dimensions: [0]
Return type: -

----------------------------------------
Table: Types
Name: float
----------------------------------------
Scope: 0
Type: float
Dimension: -
Parameters: -
Parameter types: -
Parameter dimensions: -
Return type: -

----------------------------------------
Table: Functions
Name: not
----------------------------------------
Scope: 0
Type: -
Dimension: -
Parameters: [i]
Parameter types: [int]
Parameter dimensions: [0]
Return type: int

----------------------------------------
Table: Functions
Name: flush
----------------------------------------
Scope: 0
Type: -
Dimension: -
Parameters: -
Parameter types: -
Parameter dimensions: -
Return type: -

----------------------------------------
Table: Functions
Name: exit
----------------------------------------
Scope: 0
Type: -
Dimension: -
Parameters: [i]
Parameter types: [int]
Parameter dimensions: [0]
Return type: -

----------------------------------------
Table: Constants
Name: 1.0
----------------------------------------
Scope: 0
Type: float
Dimension: -
Parameters: -
Parameter types: -
Parameter dimensions: -
Return type: -

----------------------------------------
Table: Variables
Name: X
----------------------------------------
Scope: 0
Type: float
Dimension: -
Parameters: -
Parameter types: -
Parameter dimensions: -
Return type: -

----------------------------------------
Table: Functions
Name: print
----------------------------------------
Scope: 0
Type: -
Dimension: -
Parameters: [X]
Parameter types: [int]
Parameter dimensions: [0]
Return type: -

----------------------------------------
Table: Constants
Name: 0.0
----------------------------------------
Scope: 0
Type: float
Dimension: -
Parameters: -
Parameter types: -
Parameter dimensions: -
Return type: -

----------------------------------------
Table: Constants
Name: 5
----------------------------------------
Scope: 0
Type: int
Dimension: -
Parameters: -
Parameter types: -
Parameter dimensions: -
Return type: -

----------------------------------------
Table: Variables
Name: Y
----------------------------------------
Scope: 0
Type: float
Dimension: -
Parameters: -
Parameter types: -
Parameter dimensions: -
Return type: -

----------------------------------------
Table: Variables
Name: X
----------------------------------------
Scope: 1
Type: int
Dimension: -
Parameters: -
Parameter types: -
Parameter dimensions: -
Return type: -

